#============================================================#
# PC Bang Point                                        -#
#-------------------------------------------------------------#
#Habilita o PC BANG
PcBangPointEnable = True
#LEVEL MINIMO PARA RECEBER O PC BANG
PcBangPointMinLevel = 1

#Quantidade minima de Pontos PCBANG
PcBangPointMinCount = 1
#Quantidade Max de Pontos PC BANG
PcBangPointMaxCount = 2
#CHANCE DE DUPLICAR
PcBangPointDualChance = 10

#TimeStamp em Segundos
PcBangPointTimeStamp = 900




#Kamael Restriction
KamaelCreateRestriction = True