
    	version=2340
    	builddate=20091228_1604 
      detailed info:
          file:///var/www/svn/L2J/branches/L2_GameServer_T1.5
          file:///var/www/svn/L2J
          2008-08-13T14:30:55.336671Z
          2340
          nBd
