
      version=4995
      builddate=20080813_1453
      detailed info:
          file:///var/www/svn/L2J-DP/trunk/datapack_development
          file:///var/www/svn/L2J-DP
          2008-08-13T14:31:31.947455Z
          4994
          Kerberos
